#!/usr/bin/env bash
set -euo pipefail

# Unified management entrypoint for BitShares CCXT Bridge
# Provides install, configure, start/stop, test, and OctoBot profile integration.

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PORT_DEFAULT=8787

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

print_info() { echo -e "${GREEN}[INFO]${NC} $1"; }
print_warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
print_err() { echo -e "${RED}[ERROR]${NC} $1" 1>&2; }

command_exists() { command -v "$1" >/dev/null 2>&1; }

validate_account_name() {
  local account="$1"
  [[ "$account" =~ ^[a-z][a-z0-9.-]*[a-z0-9]$ ]] && [ ${#account} -ge 3 ] && [ ${#account} -le 63 ]
}

validate_private_key() {
  local key="$1"
  [[ "$key" =~ ^5[123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz]{49,52}$ ]]
}

banned_ports=(8000 8080 3000 4000 6006 6660 6661 6662 6663 6664 6665 6666 6667 6668 6669)

port_is_banned() {
  local p="$1"
  for b in "${banned_ports[@]}"; do
    [[ "$p" == "$b" ]] && return 0
  done
  return 1
}

port_in_use() {
  local p="$1"
  lsof -Pi ":$p" -sTCP:LISTEN -t >/dev/null 2>&1
}

load_env_default() {
  local key="$1" fallback="$2"
  if [ -f "$ROOT_DIR/.env" ]; then
    local val
    val=$(grep -E "^${key}=" "$ROOT_DIR/.env" | head -n1 | cut -d'=' -f2- | tr -d '"' | tr -d "'")
    if [ -n "$val" ]; then
      echo "$val"
      return
    fi
  fi
  echo "$fallback"
}

prompt_value() {
  local prompt_text="$1" default_value="$2" secret="$3" validator="$4" error_msg="$5"
  local value
  while true; do
    if [ -n "$default_value" ]; then
      echo -n "$prompt_text [$default_value]: " >&2
    else
      echo -n "$prompt_text: " >&2
    fi
    if [ "$secret" = "true" ]; then
      read -rs value
      echo >&2
    else
      read -r value
    fi
    [ -z "$value" ] && value="$default_value"
    if [ -n "$validator" ]; then
      if "$validator" "$value"; then
        echo "$value"
        return
      else
        print_err "$error_msg"
      fi
    else
      echo "$value"
      return
    fi
  done
}

ensure_port_ready() {
  local p="$1"
  if port_is_banned "$p"; then
    print_err "Port $p is disallowed. Choose another port."
    exit 1
  fi
  if port_in_use "$p"; then
    print_err "Port $p is already in use. Stop the process or choose a different port."
    exit 1
  fi
}

write_env() {
  local bts_node="$1" bts_account="$2" bts_wif="$3" xbts_api="$4" port="$5" view_only="$6"
  cat > "$ROOT_DIR/.env" <<EOF
# BitShares CCXT Bridge Configuration
# Generated by manage.sh on $(date)

BTS_NODE=$bts_node
BTS_ACCOUNT=$bts_account
BTS_WIF=$bts_wif
BTS_VIEW_ONLY=$view_only
XBTS_API=$xbts_api
PORT=$port
NODE_ENV=production
EOF
  chmod 600 "$ROOT_DIR/.env"
  print_info "Configuration written to .env"
}

configure() {
  print_info "Configuring BitShares CCXT Bridge"
  local current_node current_account current_wif current_api current_port current_view_only
  current_node=$(load_env_default "BTS_NODE" "wss://node.xbts.io/ws")
  current_account=$(load_env_default "BTS_ACCOUNT" "")
  current_wif=$(load_env_default "BTS_WIF" "")
  current_view_only=$(load_env_default "BTS_VIEW_ONLY" "")
  current_api=$(load_env_default "XBTS_API" "https://cmc.xbts.io/v2")
  current_port=$(load_env_default "PORT" "$PORT_DEFAULT")

  if [ -z "$current_view_only" ]; then
    if [ -z "$current_wif" ]; then
      current_view_only="true"
    else
      current_view_only="false"
    fi
  fi

  local bts_node bts_account bts_wif xbts_api port view_only_mode
  bts_node=$(prompt_value "BitShares node WebSocket URL" "$current_node" "false" "true" "")
  bts_account=$(prompt_value "BitShares account name" "$current_account" "false" validate_account_name "Invalid account format. Use lowercase letters, numbers, dots, hyphens; length 3-63.")

  while true; do
    if [ "$current_view_only" = "true" ]; then
      echo -n "Enable view-only mode (no trading key required)? [Y/n]: "
    else
      echo -n "Enable view-only mode (no trading key required)? [y/N]: "
    fi
    read -r view_only_mode
    [ -z "$view_only_mode" ] && view_only_mode="$current_view_only"
    case "${view_only_mode,,}" in
      y|yes|true)
        current_view_only="true"
        bts_wif=""
        break
        ;;
      n|no|false)
        current_view_only="false"
        bts_wif=$(prompt_value "BitShares ACTIVE private key (required for trading mode)" "$current_wif" "true" validate_private_key "Invalid WIF key. It must start with 5 and be 50-53 chars.")
        break
        ;;
      *)
        print_err "Please answer yes or no."
        ;;
    esac
  done

  xbts_api=$(prompt_value "XBTS market data API" "$current_api" "false" "true" "")

  while true; do
    port=$(prompt_value "HTTP port for the bridge" "$current_port" "false" "true" "")
    if [[ "$port" =~ ^[0-9]+$ ]] && [ "$port" -ge 1024 ] && [ "$port" -le 65535 ]; then
      ensure_port_ready "$port"
      break
    else
      print_err "Port must be an integer between 1024 and 65535."
    fi
  done

  write_env "$bts_node" "$bts_account" "$bts_wif" "$xbts_api" "$port" "$current_view_only"
}

install() {
  if ! command_exists node; then
    print_err "Node.js is required. Install Node.js 20+ then rerun manage.sh install."
    exit 1
  fi
  if ! command_exists npm; then
    print_err "npm is required. Install Node.js/npm then rerun."
    exit 1
  fi

  if [ ! -f "$ROOT_DIR/.env" ]; then
    configure
  else
    print_info ".env already exists. Run 'manage.sh configure' to update if needed."
  fi

  print_info "Installing Node dependencies..."
  (cd "$ROOT_DIR" && npm install)

  print_info "Building project..."
  (cd "$ROOT_DIR" && npm run build)

  print_info "Install complete. Use './manage.sh start' to launch the bridge."
}

start_server() {
  (cd "$ROOT_DIR" && bash ./control.sh start)
}

stop_server() {
  (cd "$ROOT_DIR" && bash ./control.sh stop)
}

status_server() {
  (cd "$ROOT_DIR" && bash ./control.sh status)
}

test_suite() {
  (cd "$ROOT_DIR" && bash ./test-e2e.sh)
}

octobot_profile() {
  print_info "Installing OctoBot shim into a profile"
  if ! command_exists uv; then
    print_err "uv is required for Python installs. Install uv (https://github.com/astral-sh/uv) and retry."
    exit 1
  fi

  local profile_path python_bin
  while true; do
    echo -n "Enter OctoBot profile directory (absolute path): "
    read -r profile_path
    if [ -d "$profile_path" ]; then
      break
    else
      print_err "Directory not found: $profile_path"
    fi
  done

  if [ -x "$profile_path/.venv/bin/python" ]; then
    python_bin="$profile_path/.venv/bin/python"
  elif [ -x "$profile_path/venv/bin/python" ]; then
    python_bin="$profile_path/venv/bin/python"
  else
    echo -n "Enter Python interpreter inside the OctoBot profile: "
    read -r python_bin
  fi

  if [ ! -x "$python_bin" ]; then
    print_err "Python interpreter not executable: $python_bin"
    exit 1
  fi

  print_info "Installing octobot_shim into the OctoBot environment via uv..."
  uv pip install --python "$python_bin" --editable "$ROOT_DIR/octobot_shim"
  print_info "OctoBot shim installed. Restart OctoBot to load ccxt.bitshares_dex."
}

usage() {
  cat <<EOF
Usage: ./manage.sh <command>

Commands:
  install           Install Node deps, build, and prompt configuration
  configure         (Re)generate .env with validation
  start             Start the bridge (delegates to control.sh)
  stop              Stop the bridge (delegates to control.sh)
  status            Check server/port status
  test              Run end-to-end suite (starts/stops as needed)
  octobot-profile   Install the OctoBot shim into a given profile via uv
  help              Show this message
EOF
}

cmd="${1:-help}"
case "$cmd" in
  install) install ;;
  configure) configure ;;
  start) start_server ;;
  stop) stop_server ;;
  status) status_server ;;
  test) test_suite ;;
  octobot-profile) octobot_profile ;;
  help|*) usage ;;
esac
